### ISSUE TITLE
Fix responsiveness of the schedule and landing pages.

### ISSUE THREAD

**Issue by CDDR1** [KyoshiNoda/ScheduleFinder#132]
- [x] Make Landing Page responsive.
- [x] Make Schedule Page responsive.
- [x] Make Compare Schedule Page responsive. 
- [x] Fix responsiveness in the Account Page.
- [x] Fix responsiveness in the Sign Up page.
- [x] Fix responsiveness in the Log In page.
- [x] Fix responsiveness of the Time Slot modal.

**Comment by KyoshiNoda** [comment]
Within this Issue, can you please remove non-function UI pieces? We can tackle that in the next upcoming version. Thank you!

**Comment by CDDR1** [comment]
> Within this Issue, can you please remove non-function UI pieces? We can tackle that in the next upcoming version. Thank you!

sure!

**Comment by CDDR1** [comment]
> Within this Issue, can you please remove non-function UI pieces? We can tackle that in the next upcoming version. Thank you!

With this do you mean components that are not being currently used?
