### ISSUE TITLE
Fix broken dark theme toggle

### ISSUE THREAD

**Issue by CDDR1** [KyoshiNoda/ScheduleFinder#150]
This issue represents the work needed to fix the dark theme toggle. Currently, the dark mode is based off the user's operating system preferences, but if the user clicks the toggle, the theme will go back to the operating system's theme when there's a refresh or when the user navigates to another page. The correct behavior is that the theme remains the same when there's a refresh or when the users goes to another page.

**Comment by KyoshiNoda** [comment]
You can look into this by using redux and change the local storage to save the new data @CDDR1
