### ISSUE TITLE
Add success toasts

### ISSUE THREAD

**Issue by CDDR1** [KyoshiNoda/ScheduleFinder#174]
### **Description**
We should add a success toast for the different actions that the users can perform in the app. 

### **Acceptance Criteria**
The toast has been implemented for the following actions:
- [x] New time slot(s) added
- [x] Time slot deleted
- [x] Schedule is cleared
- [x] Email is updated
- [x] Password is updated
- [x] Personal information is updated
- [x] Friend is removed

**Comment by KyoshiNoda** [comment]
i believe we should take out account creation because it will reroute the page go the main page regardless.

**Comment by CDDR1** [comment]
> i believe we should take out account creation because it will reroute the page go the main page regardless.

Sounds good. I also don't think most pages have a success toast for when an account is created, so it makes sense to take it out.
