### ISSUE TITLE
Fix schedule bug

### ISSUE THREAD

**Issue by CDDR1** [KyoshiNoda/ScheduleFinder#247]
### **Description** 
The schedule won't let me add an interval that ends at 12:00 PM. It might be an issue with how the input validation is being done.

<details>
  <summary>Video of the bug</summary>

https://github.com/KyoshiNoda/ScheduleFinder/assets/62437724/d5a22adb-780b-4a1c-91d3-4bac824a0133

</details>

<details>
  <summary>Error message</summary>

<img width="1707" alt="Screenshot 2024-01-06 at 8 46 20 PM" src="https://github.com/KyoshiNoda/ScheduleFinder/assets/62437724/d1895263-2952-461f-8844-03c2a8382597">

</details>

### **Acceptance Criteria**
- [ ] Adding an interval that ends at 12:00 PM is possible.
- [ ] Schedule functionality is fully fixed.

**Comment by KyoshiNoda** [comment]
### Notes
- It seems this bug exist in the morning time sections. If you make a timeSlot after 2 pm it seems to work as exepected.
- A temporary fix would be to make a working `TimeSlot` past 2pm and edit it in place afterwards. 

### Screenshots/Logs
- FIX: compareSchedule isn't working.
 Cannot read properties of undefined (reading 'startTime')


![Image](https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/09447cd6-fb0a-4e46-98b2-51fe27db0513)
- no error modal or timeslot (problem seems to exist on the mornings.) 

![Image](https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/369667c6-542d-4297-8961-f8b7e2e8d340)

![Image](https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/060596ce-51a8-4162-a298-2212fa66c497)
